### ISSUE TITLE
Weekly scrum - March 10, 2021

### ISSUE THREAD

**Issue by SoniaHL** [mounicap6/SYSC4806#15]
Everyone should write: 
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

**Comment by mounicap6** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- worked on the heroku implementation and linking the github for deployment #1 
- implemented a simple html to display the results #16 

what will I do next week? (with link(s) to the relevant GitHub Issue(s)) 
- TBD

**Comment by sarahlamonica** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- contributed to Book.java and BookStore.java #4 
- set up the database #4 
- implemented JPA in the Book and BookStore classes #4 

what will I do next week? (with link(s) to the relevant GitHub Issue(s))

- TBD

what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

- Solved: BufferedImage caused some issues in the persistence. Commented out for now and will revisit at a later date.

**Comment by shoana** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- Worked on integrating Travis with GitHub 
- Worked on integrating Travis Heroku

what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- TBD

what is holding me back? (if applicable)
ERROR: The command "eval mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V " failed. Retrying, 3 of 3.

#18

**Comment by SoniaHL** [comment]
what have I done this week?

- Implemented the Book.java and BookStore.java classes  #6 
- Created the UML diagram for the above mentioned classes #9 

what will I do next week? 

- TBD

**Comment by lynnmehyou** [comment]
what have I done this week? 

* worked on testing  #3 
* worked on the README.MD #3 

what will I do next week? (with link(s) to the relevant GitHub Issue(s))
TBD
