### ISSUE TITLE
Weekly Scrum - March 12, 2020

### ISSUE THREAD

**Issue by SoniaHL** [mounicap6/SYSC4806#45]
Everyone should write:

what have I done this week? (with link(s) to the relevant GitHub Issue(s))
what will I do next week? (with link(s) to the relevant GitHub Issue(s))
what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

**Comment by mounicap6** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- create html page for owner to upload a new book
- created get and post methods for uploading a new book
- created a link between the main page and upload page

what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- saving the new book uploaded by the owner to the database

what is holding me back? (if applicable)
- rest controller issues

**Comment by shoana** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- Working on creating the checkout page #42 

what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- Continue to work on the page 
- Work on testing

**Comment by SoniaHL** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- Implemented an inventory #40 
what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- Implement roles (depending on if Owner or User, different pages/functionality available) #44

**Comment by sarahlamonica** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- Implemented add to cart functionality #53 
- Add cart to main bookstore page
what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- Add to cart #53 
what is holding me back? (if applicable)
- N/A

**Comment by lynnmehyou** [comment]
what have I done this week? 
created a delete button to delete a book #39
