### ISSUE TITLE
Weekly Scrum - March 19, 2021

### ISSUE THREAD

**Issue by mounicap6** [mounicap6/SYSC4806#54]
Everyone should write:

what have I done this week? (with link(s) to the relevant GitHub Issue(s))
what will I do next week? (with link(s) to the relevant GitHub Issue(s))
what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

**Comment by sarahlamonica** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- Implemented Add to Cart functionality #53 

what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- TBA

what is holding me back? (if applicable)
- Add to Cart currently only allows 1 book per cart

**Comment by shoana** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- Added the checkout page to the application #42 

what will I do next week? (with link(s) to the relevant GitHub Issue(s))

- TBA

**Comment by mounicap6** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s)) #38 #52
- added JS to editbookstore.html and bookstore.html
- creating bookrepo to store the owner's new book uploads 
what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- TBD
- separating user and owner functionality

**Comment by SoniaHL** [comment]
what have I done this week?
- Implemented roles to differentiate between owner and user #44 
what will I do next week? 
- TDB

**Comment by lynnmehyou** [comment]
what have I done this week? 
worked on having a button to edit the information of a book  
what will I do next week? 
will continue to work on this
tbd
