### ISSUE TITLE
Weekly Scrum - April 2, 2021

### ISSUE THREAD

**Issue by shoana** [mounicap6/SYSC4806#63]
Everyone should write:

what have I done this week? (with link(s) to the relevant GitHub Issue(s))
what will I do next week? (with link(s) to the relevant GitHub Issue(s))
what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

**Comment by mounicap6** [comment]
what have I done this week? 
- generated a dropdown for genres instead of user input 
- added javascript to upload book functionality 
what will I do next week? #61 
- continue to work on the recommendation functionality

**Comment by SoniaHL** [comment]
what have I done this week?
- started looking into database setup (been reading through tutorials to find the best one)
- started researching websockets
what will I do next week? 
- implement the database setup
- work on the oral presentation

**Comment by shoana** [comment]
what have I done this week?

- Continuing to work on the checkout page

what will I do next week?
- Research springboot WebSocket examples 
- Work on the presentation slides 
- Implement the checkout page

**Comment by sarahlamonica** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

Implemented Add to Cart functionality #53
Added shopping cart to main html page
what will I do next week? (with link(s) to the relevant GitHub Issue(s))

Implementing Quantity and Book Prices in Shopping Cart and Checkout Page 
Fix bug: Add to Cart currently only allows 1 book per cart

**Comment by lynnmehyou** [comment]
what have I done this week? 
I have implemented the delete button
what will I do next week? 
will implement having a picture for the book
