### ISSUE TITLE
Weekly Scrum - April 9, 2021

### ISSUE THREAD

**Issue by SoniaHL** [mounicap6/SYSC4806#85]
Everyone should write:

what have I done this week? (with link(s) to the relevant GitHub Issue(s))
what will I do next week? (with link(s) to the relevant GitHub Issue(s))
what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

**Comment by SoniaHL** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- Added sort functionality #65 
- Added search #64 
- Added User class #69 
- Added MockMVC tests for BookStoreController #72

**Comment by shoana** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- Add inventory #86 
- Helped with shopping cart + checkout #81 
- Added tests + MockMVC for the respected changes #77 #87

**Comment by sarahlamonica** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- Implemented all shopping cart functionality #60 
- Implemented unique shopping cart for to each user, added user a #77 
- Implemented checkout page #42

**Comment by mounicap6** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- recommendation functionality  #61 #67
- jaccard distance and tests #87
- inventroy modifiactions (front end bug fixes) #86 #83

**Comment by lynnmehyou** [comment]
what have I done this week?
* delete button #39 
* added picture in the book's info
